[profile.default]
src = 'contracts'
test = 'foundry-test'
out = 'artifacts'
libs = ['lib', 'node_modules']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'erc-payable-token/=node_modules/erc-payable-token/',
    'hardhat/=node_modules/hardhat/',
    'sgn-v2-contracts/=lib/sgn-v2-contracts/',
    'forge-std/=lib/forge-std/src/',
]
solc_version = '0.8.9'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config