name: Hardhat test

on:
  pull_request:
    branches: [main]
jobs:
  run-hardhat-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.12]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install latest Yarn
        run: corepack prepare yarn@stable --activate
      - name: Activate latest Yarn
        run: yarn set version stable
      - run: yarn config set -H enableImmutableInstalls false
      - name: Install Node.js dependencies
        run: yarn install
      - name: Install hardhat
        run: yarn add hardhat@^2.19.4
      - run: npx hardhat compile
      - run: npx hardhat test